### ISSUE TITLE
Task 5. Simplify some methods

### ISSUE THREAD

**Issue by SergioV85** [vposidailo/angular-mentee-program#1]
https://github.com/vposidailo/angular-mentee-program/blob/d83d17987e1e72a54ff32d94bb6b4f6de9e0eac2/src/app/app.component.ts#L19

You use a simple getter, like 
` get checkIfUserLogin(): boolean`
So, in the component, you can write
`*ngIf="checkIfUserLogin">`
like a value, not a method.

**Comment by vposidailo** [comment]
Fixed
