### ISSUE TITLE
Task 5. Creating new item

### ISSUE THREAD

**Issue by SergioV85** [vposidailo/angular-mentee-program#2]
https://github.com/vposidailo/angular-mentee-program/blob/d83d17987e1e72a54ff32d94bb6b4f6de9e0eac2/src/app/_shared/services/video_courses_service/video-courses-service.service.ts#L106

Please, explain this "construction". Why we have a comparison operator and return a boolean value from "Create" method.

**Comment by vposidailo** [comment]
Fixed.
