### ISSUE TITLE
Task 5: Deleting the course

### ISSUE THREAD

**Issue by SergioV85** [vposidailo/angular-mentee-program#4]
https://github.com/vposidailo/angular-mentee-program/blob/d83d17987e1e72a54ff32d94bb6b4f6de9e0eac2/src/app/_shared/services/video_courses_service/video-courses-service.service.ts#L109

You shouldn't accept the array from the method. From the component, you will get item object only, or even just item id. You should find the proper item in the existed list in your service `private videoCourseSource`, delete there, and return new `this.videoCourseSource`.

Or, even, go a bit forward: use RxJS Subjects for storing the list, and subscribe for the data from Subject in related components. So, you can implement next approach:
1. Create an empty Subject
2. In the `video-courses-list-component.component.ts` subscribe to this Subject.
3. On "GET" request push a mocked list to the Subject.
3*. Your component will automatically update with new data and re-render the list with new items
4. On "Create" request get a list from the Subject, push a new item to it and update the Subject.
4*. Your component will automatically update with new data and re-render the list with the new item.
5. On "Delete" request get a list from the Subject, remove an item from it, and push modified list to the Subject.
5*. Your component will automatically update with new data and re-render the list with the new item.

**Comment by vposidailo** [comment]
Fixed. Refactored video course service.
