### ISSUE TITLE
Taks 5. Mixed logic in UpdateItem method

### ISSUE THREAD

**Issue by SergioV85** [vposidailo/angular-mentee-program#6]
https://github.com/vposidailo/angular-mentee-program/blob/6a3dc396132c6a5896aa559ac8b5ffdeb6ffacc3/src/app/_shared/services/video_courses_service/video-courses-service.service.ts#L120

Probably should be vice versa:
if we **find** element (`updateItemIndex > -1`), we should update it (replace in the list with new object), and if **didn't find** - return a list OR add a new item to the end (works like a creation).

**Comment by vposidailo** [comment]
Thx. Good catch. Done.
